### ISSUE TITLE
アプリ終了時に例外が発生する

### ISSUE THREAD

**Issue by noboru-i** [noboru-i/kyouen-android#4]
```
java.lang.RuntimeException: Unable to destroy activity {hm.orz.chaos114.android.tumekyouen/hm.orz.chaos114.android.tumekyouen.TitleActivity}: java.lang.IllegalArgumentException: Receiver not registered: com.google.android.gcm.GCMBroadcastReceiver@47b26eb8
at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:3655)
at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:3673)
at android.app.ActivityThread.access$2900(ActivityThread.java:125)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:123)
at android.app.ActivityThread.main(ActivityThread.java:4627)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:521)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:871)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:629)
at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.IllegalArgumentException: Receiver not registered: com.google.android.gcm.GCMBroadcastReceiver@47b26eb8
at android.app.ActivityThread$PackageInfo.forgetReceiverDispatcher(ActivityThread.java:793)
at android.app.ContextImpl.unregisterReceiver(ContextImpl.java:897)
at android.content.ContextWrapper.unregisterReceiver(ContextWrapper.java:331)
at com.google.android.gcm.GCMRegistrar.onDestroy(GCMRegistrar.java:266)
at hm.orz.chaos114.android.tumekyouen.TitleActivity.onDestroy(TitleActivity.java:272)
at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:3642)
... 11 more
```

**Comment by noboru-i** [comment]
done
